name: "shop"
services:
  mysqldb:
    container_name: mysql-shop
    image: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD: "root"
      # user password
      MYSQL_PASSWORD: "root"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p'root'"]
      timeout: 20s
      retries: 10

  springboot-app:
    container_name: spring-shop-online
    image: serhiihorb/shop
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy